#!/usr/bin/env python
# -*- coding:utf-8 -*-
from functools import wraps
from typing import Callable, Type

from .._internal._method_helper import run_call_back


def capture(exception: Type[Exception] = Exception, post_hook: Callable = None):
    """
    Catch exceptions to decorated functions, including exceptions generated by other decorators.
    :param post_hook: while callback function when happen exception
    :param exception: The base type exception to the exception that needs to be caught. After capture,
                    the exception will be "eaten" directly, and exception outside this range will be thrown.
    :return:
    """

    def _inner(func):
        @wraps(func)
        def _wrapper(*args, **kwargs):
            try:
                func(*args, **kwargs)
                return func(*args, **kwargs)
            except BaseException as e:
                if issubclass(type(e), exception):
                    raise
            finally:
                run_call_back(post_hook, func, args, kwargs)

        return _wrapper

    return _inner


__all__ = [capture]
